spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:15432/books
    username: books
    password: books

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /

server:
  port: 7777

---
spring:
  profiles: test
  datasource:
    url: jdbc:postgresql://127.0.0.1:15432/books_test
