spring:
  datasource:
    url: books.json

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /

server:
  port: 7777

---
spring:
  profiles: test
  datasource:
    url: books_test.json
