spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/books
    username: books
    password: books

server:
  port: 8000

---
spring:
  profiles: test
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/books_test
app:
  debug: false
